source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Kash_Example', :exclusive => true do
  pod "Kash", :path => "../"
end

target 'Kash_Tests', :exclusive => true do
  pod "Kash", :path => "../"

  
end
